#FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04
#FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04
FROM conda/miniconda3

ARG USER_ID
ARG GROUP_ID

RUN addgroup --gid $GROUP_ID user || true
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID user
RUN chmod -R 777 /home


RUN mkdir /workdir
WORKDIR /workdir
COPY docker_entry_script.sh /workdir/docker_entry_script.sh
RUN chmod ugo+rx /workdir/docker_entry_script.sh
USER user
RUN ls -l /home
RUN conda init bash
RUN conda create --name relaqs
RUN echo "source /workdir/docker_entry_script.sh" >> ~/.bashrc



#ENTRYPOINT ["/workdir/docker_entry_script.sh"]


#RUN git clone git@github.com:akataba/rl-repo.git
#RUN python3 -m venv /workdir/venv
#ENV PATH="/workdir/venv/bin:$PATH"

